### ISSUE TITLE
Feature request: keyboard shortcuts

### ISSUE THREAD

**Issue by lucmp** [Edd12321/zrc#5]
I don't see keyboard shortcuts in your TODO list so I thought I might as well ask for it. I really miss:

- Ctrl+l: clear
- Home/Ctrl+a: jump to beginning of line
- End/Ctrl+e: jump to end of line
- Alt+up: cd ..
- Alt+left: cd -

Among others.

By the way, I use Linux but I really like the CHM format for studying so I made myself one out of your man pages. It is attached. Feel free to distribute it if you like.

Here: [zrc.chm.zip](https://github.com/Edd12321/zrc/files/12518679/zrc.chm.zip)

Please don't count on me to update it often. It involves a lot of editing and Microsoft makes the building procedure considerably more difficult than it had to be.

Also I won't be around here for long. Github will soon enforce two-factor authentication and I will not comply because it requires a phone number or a phone application (which of course collects personal data) and I find that invasive and abusive. So I may not be able to log in and comment anymore.

Thank you for your attention.

**Comment by Edd12321** [comment]
The most simple and unix-y solution to this just would be adding a `bind` command (like the Bourne Again shell) and letting the user define his own keybindings which "send" other keys than the ones actually typed. Then you could so something like

`bind (weird terminal escape sequence) clear\n`

I'm looking forward to implementing this feature until v1.0 because, personally, I also miss some keybindings myself. It should be easy to do this using `termios.h`, given enough time to polish it.

Now, a tangent on the topic of GitHub: it's truly sad to see what this website has become. I can add either GitLab or Bitbucket as a second remote (together with GitHub), which currently don't require 2FA to use. I've always wanted to try out these hosting services, as it's getting clearer by the day that GitHub is full of anti-consumer and privacy invasive practices (even though I've given in and just put my phone number).

Though, if you really won't stick around for the ride either way, thanks for the .chm documentation file, and thanks for all of the feedback and issues opened so far. It's been a fun journey from start to finish.

**Comment by Edd12321** [comment]
Good news! The custom keybind feature is 90% done. I just need to fix a bug that appears when you use arrow keys, write some docs and then I will push ASAP.

**Comment by Edd12321** [comment]
Keybinds now work. I've added some (including Ctrl-L) to the default .zrc file. What's nice is that `bindkey` doesn't even need its own "little language", because the substitution engine already replaces `\cX` and `\e` with the corresponding keys.

Study the man pages for more info..

**Comment by Edd12321** [comment]
Sorry for reopening this very old issue, but I just wanted to let you know that I will include your .chm in the `legacy` branch!

In case you didn't know, I've been rewriting the shell from scratch. Some syntax and command stuff was changed so I'll have to write new docs, but these are pretty useful for the old version.

**Comment by Edd12321** [comment]
f0f10f2f001c86c411fafbd7d21dd653ca8fe9a9
